// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IJobFields {
  /** title */
  title: string;

  /** percentage */
  percentage: number;

  /** company */
  company: string;

  /** dateFrom */
  dateFrom: string;

  /** dateTo */
  dateTo: string;

  /** description */
  description: Document;
}

export interface IJob extends Entry<IJobFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "job";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPostFields {
  /** title */
  title?: string | undefined;

  /** date */
  date?: string | undefined;

  /** image */
  image?: Asset | undefined;
}

export interface IPost extends Entry<IPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "post";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "job" | "post";

export type IEntry = IJob | IPost;

export type LOCALE_CODE = "de-CH" | "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
