import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import Navbar from '../components/Navbar/NavbarSelfmade'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.scss'
import './'
import Hello from "../components/Hello/Hello";
import {GetStaticProps, NextPage} from "next";
import ContentService from "../util/content-service";
import {IHelloFields, IJobFields} from "../@types/contentful";
import Footer from "../components/Footer/Footer";


interface Props {
    globalInfos: IHelloFields[];
}

//const Home: NextPage<Props> = ({ globals }) => (

/*
export default function Home() {
  return (
    <>
      <Head>
        <title>it's carla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Navbar></Navbar>
          <Hello></Hello>
      </main>
    </>
  )
}

 */

const Home: NextPage<Props> = ({ globalInfos }) => (
    <div className={styles.container}>
        <Head>
            <title>it's carla</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />

            <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png"/>
            <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png"/>
            <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png"/>
            <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png"/>
            <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png"/>
            <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png"/>
            <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png"/>
            <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png"/>
            <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png"/>
            <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png"/>
            <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
            <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png"/>
            <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
            <link rel="manifest" href="/manifest.json"/>
            <meta name="msapplication-TileColor" content="#ffffff"/>
            <meta name="msapplication-TileImage" content="/ms-icon-144x144.png"/>
            <meta name="theme-color" content="#ffffff"/>
        </Head>
        <main className={styles.main}>
            <Navbar></Navbar>
            <Hello generalInfo={globalInfos}></Hello>
        </main>
        <Footer></Footer>
    </div>
);

export default Home;


export const getStaticProps: GetStaticProps<Props> = async () => {
    const globalInfos = (
        await ContentService.instance.getEntriesByType<IHelloFields>("hello")
    ).map((entry) => entry.fields);

    return {
        props: {
            globalInfos,
        },
    };
};


