import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import Navbar from '../components/NavBar'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.scss'
import './'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>it's carla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Navbar></Navbar>
        <div className={styles.card}>
           <p>Hallo! :-)</p>
        </div>
      </main>
    </>
  )
}
